# Generated by Django 3.0.8 on 2020-07-22 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oportunity',
            name='area',
        ),
        migrations.RemoveField(
            model_name='oportunity',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='oportunity',
            name='responsabilities',
        ),
    ]
